"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={token:sessionStorage.getItem("tyxnet_token")||"",user:null,page:"dashboard",users:[],pingInterval:25};
const titles={dashboard:"Overview",devices:"Devices",users:"Users",tokens:"Enrollment tokens",commands:"Commands",audit:"Audit log"};
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const date=v=>v?new Date(v).toLocaleString():"Never";
const duration=s=>{s=Number(s||0);const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return d?`${d}d ${h}h`:h?`${h}h ${m}m`:`${m}m`;};
function toast(message,error=false){const t=$("#toast");t.textContent=message;t.className=`toast show${error?" error":""}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.className="toast",3500)}
async function api(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const response=await fetch(path,{...options,headers});if(response.status===401&&state.token){signOut();throw new Error("Your session expired.")}if(!response.ok){let msg=`Request failed (${response.status})`;try{const body=await response.json();msg=body.error?.message||msg}catch{}throw new Error(msg)}if(response.status===204)return null;return response.json()}
function setToken(token){state.token=token||"";if(token)sessionStorage.setItem("tyxnet_token",token);else sessionStorage.removeItem("tyxnet_token")}
function showAuth(view){$("#console").hidden=true;$("#auth").hidden=false;["setup-view","setup-disabled","login-view"].forEach(id=>$("#"+id).hidden=id!==view);$("#auth-error").textContent=""}
async function boot(){try{const setup=await api("/api/v1/setup/status");if(setup.required){showAuth(setup.enabled?"setup-view":"setup-disabled");return}if(!state.token){showAuth("login-view");return}state.user=await api("/api/v1/auth/me");showConsole()}catch(e){showAuth("login-view");$("#auth-error").textContent=e.message}}
function showConsole(){$("#auth").hidden=true;$("#console").hidden=false;$("#account-name").textContent=state.user.Username;$("#account-role").textContent=state.user.Role;openPage("dashboard")}
function signOut(){setToken("");state.user=null;showAuth("login-view")}
async function submitAuth(form,path){const data=Object.fromEntries(new FormData(form));if(path.includes("setup")&&data.password!==data.confirm)throw new Error("Passwords do not match.");delete data.confirm;const result=await api(path,{method:"POST",body:JSON.stringify(data)});setToken(result.access_token);state.user=result.user;showConsole()}
async function openPage(page){state.page=page;$("#page-title").textContent=titles[page];$$('.page').forEach(x=>x.hidden=x.id!==`page-${page}`);$$('#nav button').forEach(x=>x.classList.toggle("active",x.dataset.page===page));try{await loaders[page]()}catch(e){toast(e.message,true)}}
const loaders={dashboard:loadDashboard,devices:loadDevices,users:loadUsers,tokens:loadTokens,commands:loadCommands,audit:loadAudit};
async function loadDashboard(refreshSettings=true){const s=await api("/api/v1/server/status");state.pingInterval=Number(s.ping_interval_seconds||25);const adapter=s.adapter_ready?`${s.adapter_name} (${s.adapter_address})`:"Disabled";const stats=[["Users",s.users],["Devices",s.devices],["Online",s.online_devices],["Offline",s.offline_devices],["Adapter",adapter],["Ping interval",`${state.pingInterval}s`],["Uptime",duration(s.uptime_seconds)]];$("#stats").innerHTML=stats.map(([k,v])=>`<div class="stat"><small>${esc(k)}</small><strong>${esc(v)}</strong></div>`).join("");const settings=$("#ping-settings");settings.hidden=state.user.Role!=="admin";if(refreshSettings){if(!settings.hidden)$("#ping-form").elements.ping_interval_seconds.value=state.pingInterval;await loadStartup()}}
async function loadStartup(){const panel=$("#startup-settings");panel.hidden=state.user.Role!=="admin";if(panel.hidden)return;const result=await api("/api/v1/server/startup");$("#startup-enabled").checked=result.enabled}
async function loadDevices(){const rows=await api("/api/v1/devices"),isAdmin=state.user.Role==="admin";$("#devices-body").innerHTML=rows.length?rows.map(d=>`<tr><td><strong>${esc(d.Name)}</strong><br><small>${esc(d.ID)}</small></td><td><code>${esc(d.VirtualIP)}</code></td><td>${esc(d.OS)} / ${esc(d.Arch)}<br><small>${esc(d.Version)}</small></td><td><span class="badge ${d.Revoked?"danger":d.Online?"success":""}">${d.Revoked?"Revoked":d.Online?"Online":"Offline"}</span></td><td>${date(d.LastSeen)}</td><td><div class="actions" data-device="${esc(d.ID)}" data-name="${esc(d.Name)}" data-ip="${esc(d.VirtualIP)}"><button data-action="rename">Rename</button>${isAdmin?'<button data-action="set-ip">Set IP</button>':""}<button data-action="disconnect" ${d.Revoked?"disabled":""}>Disconnect</button><button data-action="restart" ${d.Revoked?"disabled":""}>Restart</button><button data-action="shutdown" ${d.Revoked?"disabled":""}>Shutdown</button><button class="danger" data-action="revoke" ${d.Revoked?"disabled":""}>Revoke</button></div></td></tr>`).join(""):`<tr><td colspan="6" class="muted">No devices enrolled yet.</td></tr>`}
async function loadUsers(){state.users=await api("/api/v1/users");$("#token-user").innerHTML=state.users.filter(u=>!u.Disabled).map(u=>`<option value="${esc(u.ID)}">${esc(u.Username)}</option>`).join("");$("#users-body").innerHTML=state.users.map(u=>`<tr><td><strong>${esc(u.Username)}</strong><br><small>${esc(u.ID)}</small></td><td><select data-role="${esc(u.ID)}" ${u.ID===state.user.ID?"disabled":""}>${["admin","operator","member","viewer"].map(r=>`<option ${r===u.Role?"selected":""}>${r}</option>`).join("")}</select></td><td><span class="badge ${u.Disabled?"danger":"success"}">${u.Disabled?"Disabled":"Active"}</span></td><td>${date(u.CreatedAt)}</td><td><div class="actions" data-user="${esc(u.ID)}" data-disabled="${u.Disabled}"><button data-action="toggle" ${u.ID===state.user.ID?"disabled":""}>${u.Disabled?"Enable":"Disable"}</button><button class="danger" data-action="delete" ${u.ID===state.user.ID?"disabled":""}>Delete</button></div></td></tr>`).join("")}
async function loadTokens(){if(!state.users.length)state.users=await api("/api/v1/users");const names=Object.fromEntries(state.users.map(u=>[u.ID,u.Username]));$("#token-user").innerHTML=state.users.filter(u=>!u.Disabled).map(u=>`<option value="${esc(u.ID)}">${esc(u.Username)}</option>`).join("");const rows=await api("/api/v1/tokens");$("#tokens-body").innerHTML=rows.length?rows.map(t=>`<tr><td><code>${esc(t.ID)}</code></td><td>${esc(names[t.UserID]||t.UserID)}</td><td>${date(t.ExpiresAt)}</td><td>${esc(t.Uses)} / ${esc(t.MaxUses)}</td><td><span class="badge ${t.Revoked?"danger":new Date(t.ExpiresAt)<new Date()?"warning":"success"}">${t.Revoked?"Revoked":new Date(t.ExpiresAt)<new Date()?"Expired":"Active"}</span></td><td><div class="actions" data-token="${esc(t.ID)}"><button class="danger" data-action="revoke" ${t.Revoked?"disabled":""}>Revoke</button></div></td></tr>`).join(""):`<tr><td colspan="6" class="muted">No enrollment tokens created.</td></tr>`}
async function loadCommands(){const rows=await api("/api/v1/commands");$("#commands-body").innerHTML=rows.length?rows.map(c=>`<tr><td><code>${esc(c.ID)}</code></td><td><code>${esc(c.DeviceID)}</code></td><td>${esc(c.Type)}</td><td><span class="badge">${esc(c.Status)}</span></td><td>${date(c.CreatedAt)}</td><td>${date(c.ExpiresAt)}</td></tr>`).join(""):`<tr><td colspan="6" class="muted">No commands queued.</td></tr>`}
async function loadAudit(){const rows=await api("/api/v1/audit");$("#audit-body").innerHTML=rows.length?rows.map(a=>`<tr><td>${date(a.CreatedAt)}</td><td><strong>${esc(a.Action)}</strong></td><td><code>${esc(a.ActorID||"system")}</code></td><td><code>${esc(a.TargetID||"â€”")}</code></td><td>${esc(a.RemoteIP)}</td></tr>`).join(""):`<tr><td colspan="5" class="muted">No audit events.</td></tr>`}
$("#setup-form").addEventListener("submit",async e=>{e.preventDefault();try{await submitAuth(e.target,"/api/v1/setup")}catch(x){$("#auth-error").textContent=x.message}});
$("#login-form").addEventListener("submit",async e=>{e.preventDefault();try{await submitAuth(e.target,"/api/v1/auth/login")}catch(x){$("#auth-error").textContent=x.message}});
$("#logout").addEventListener("click",async()=>{try{await api("/api/v1/auth/logout",{method:"POST"})}catch{}signOut()});
$("#refresh").addEventListener("click",()=>openPage(state.page));$("#nav").addEventListener("click",e=>{const b=e.target.closest("button[data-page]");if(b)openPage(b.dataset.page)});
$("#user-form").addEventListener("submit",async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{await api("/api/v1/users",{method:"POST",body:JSON.stringify(d)});e.target.reset();toast("User created.");await loadUsers()}catch(x){toast(x.message,true)}});
$("#token-form").addEventListener("submit",async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));d.max_uses=Number(d.max_uses);try{const r=await api("/api/v1/tokens",{method:"POST",body:JSON.stringify(d)});$("#secret-value").textContent=r.token;$("#secret-dialog").showModal();await loadTokens()}catch(x){toast(x.message,true)}});
$("#ping-form").addEventListener("submit",async e=>{e.preventDefault();const seconds=Number(new FormData(e.target).get("ping_interval_seconds"));try{await api("/api/v1/server/settings",{method:"PATCH",body:JSON.stringify({ping_interval_seconds:seconds})});toast("Ping interval saved.");await loadDashboard()}catch(x){toast(x.message,true)}});
$("#startup-enabled").addEventListener("change",async e=>{const enabled=e.target.checked;e.target.disabled=true;try{await api("/api/v1/server/startup",{method:"PATCH",body:JSON.stringify({enabled})});toast(enabled?"Startup enabled.":"Startup disabled.")}catch(x){e.target.checked=!enabled;toast(x.message,true)}finally{e.target.disabled=false}});
$("#copy-secret").addEventListener("click",async()=>{await navigator.clipboard.writeText($("#secret-value").textContent);toast("Token copied.")});
$("#devices-body").addEventListener("click",async e=>{const b=e.target.closest("button[data-action]");if(!b)return;const box=b.closest("[data-device]"),id=box.dataset.device,a=b.dataset.action;try{if(a==="rename"){const name=prompt("New device name",box.dataset.name);if(!name)return;await api(`/api/v1/devices/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({Name:name})})}else if(a==="set-ip"){const ip=prompt("Static TyxNet IP address",box.dataset.ip);if(!ip||ip===box.dataset.ip)return;await api(`/api/v1/devices/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({VirtualIP:ip})});toast("Static IP saved. The client will apply it on its next connection.");await loadDevices();return}else if(a==="revoke"){if(!confirm("Revoke this device? It will no longer authenticate."))return;await api(`/api/v1/devices/${encodeURIComponent(id)}`,{method:"DELETE"})}else{if((a==="restart"||a==="shutdown")&&!confirm(`Queue ${a} for this device?`))return;await api(`/api/v1/devices/${encodeURIComponent(id)}/${a}`,{method:"POST"})}toast(`Device ${a} requested.`);await loadDevices()}catch(x){toast(x.message,true)}});
$("#users-body").addEventListener("click",async e=>{const b=e.target.closest("button[data-action]");if(!b)return;const box=b.closest("[data-user]"),id=box.dataset.user,a=b.dataset.action,role=$(`[data-role="${CSS.escape(id)}"]`).value;try{if(a==="delete"){if(!confirm("Delete this user?"))return;await api(`/api/v1/users/${encodeURIComponent(id)}`,{method:"DELETE"})}else{await api(`/api/v1/users/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({Disabled:box.dataset.disabled!=="true",Role:role})})}toast("User updated.");await loadUsers()}catch(x){toast(x.message,true)}});
$("#users-body").addEventListener("change",async e=>{if(!e.target.matches("select[data-role]"))return;const id=e.target.dataset.role,u=state.users.find(x=>x.ID===id);try{await api(`/api/v1/users/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({Disabled:u.Disabled,Role:e.target.value})});toast("Role updated.");await loadUsers()}catch(x){toast(x.message,true)}});
$("#tokens-body").addEventListener("click",async e=>{const b=e.target.closest("button[data-action]");if(!b)return;const id=b.closest("[data-token]").dataset.token;if(!confirm("Revoke this enrollment token?"))return;try{await api(`/api/v1/tokens/${encodeURIComponent(id)}`,{method:"DELETE"});toast("Token revoked.");await loadTokens()}catch(x){toast(x.message,true)}});
boot();
setInterval(()=>{if(!state.user)return;if(state.page==="devices")loadDevices().catch(()=>{});else if(state.page==="dashboard")loadDashboard(false).catch(()=>{})},3000);
