"use strict";
const $=selector=>document.querySelector(selector);
const state={token:sessionStorage.getItem("tyxnet_client_token")||"",user:null,configured:false};
const esc=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
async function request(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(options.auth!==false&&state.token)headers.Authorization=`Bearer ${state.token}`;const response=await fetch(path,{...options,headers});if(!response.ok)throw new Error((await response.text()).trim()||`Request failed (${response.status})`);if(response.status===204)return null;return response.json()}
function toast(message,isError=false){const node=$("#toast");node.textContent=message;node.className=`toast show${isError?" error-toast":""}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.className="toast",3000)}
function renderLocal(local){state.configured=local.configured;$("#setup").hidden=local.configured;$("#app").hidden=!local.configured;if(!local.configured)return;$("#connection").textContent=local.connected?"Connected":"Connecting";$("#dot").classList.toggle("online",local.connected);$("#virtual-ip").textContent=local.virtual_ip||"—";$("#adapter-name").textContent=local.adapter_ready?`${local.adapter_name} (${local.adapter_address})`:"Not ready";$("#device-id").textContent=local.device_id||"—";$("#last-connected").textContent=local.last_connected&&!local.last_connected.startsWith("0001-")?new Date(local.last_connected).toLocaleString():"—";$("#last-error").textContent=local.last_error||""}
async function refreshLocal(){try{renderLocal(await request("/api/status",{auth:false}))}catch(error){$("#error").textContent=error.message}}
function showManagementLogin(){state.user=null;$("#management-login").hidden=false;$("#network-devices").hidden=true;$("#logout").hidden=true}
function showDevices(){$("#management-login").hidden=true;$("#network-devices").hidden=false;$("#logout").hidden=false;$("#role-label").textContent=`Signed in as ${state.user.Username} · ${state.user.Role}`;const panel=$("#startup-panel");panel.hidden=state.user.Role!=="admin";if(!panel.hidden)loadStartup().catch(error=>toast(error.message,true))}
async function loadStartup(){const result=await request("/api/management/startup");$("#startup-enabled").checked=result.enabled}
async function bootManagement(){if(!state.token){showManagementLogin();return}try{state.user=await request("/api/management/me");showDevices();await loadDevices()}catch{state.token="";sessionStorage.removeItem("tyxnet_client_token");showManagementLogin()}}
async function loadDevices(){const devices=await request("/api/management/devices");const canControl=["admin","operator"].includes(state.user.Role);$("#device-grid").innerHTML=devices.length?devices.map(device=>{const online=!device.Revoked&&device.Online;return `<article class="device"><div class="device-head"><div><strong>${esc(device.Name)}</strong><small>${esc(device.OS)} / ${esc(device.Arch)}</small></div><span class="badge ${online?"online":""}">${device.Revoked?"Revoked":online?"Online":"Offline"}</span></div><code>${esc(device.VirtualIP)}</code><small>${esc(device.ID)}</small>${canControl&&!device.Revoked?`<div class="actions" data-device="${esc(device.ID)}"><button data-action="disconnect">Reconnect</button><button data-action="restart">Restart</button><button data-action="shutdown" class="danger-button">Shutdown</button></div>`:""}</article>`}).join(""):`<p class="muted">No devices are visible to this role.</p>`}
$("#setup-form").addEventListener("submit",async event=>{event.preventDefault();const button=event.currentTarget.querySelector("button");button.disabled=true;$("#error").textContent="";try{await request("/api/setup",{method:"POST",auth:false,body:JSON.stringify({server:$("#server").value,name:$("#name").value,token:$("#token").value})});$("#token").value="";await refreshLocal();await bootManagement()}catch(error){$("#error").textContent=error.message}finally{button.disabled=false}});
$("#login-form").addEventListener("submit",async event=>{event.preventDefault();$("#login-error").textContent="";try{const result=await request("/api/management/login",{method:"POST",auth:false,body:JSON.stringify({username:$("#username").value,password:$("#password").value})});state.token=result.access_token;state.user=result.user;sessionStorage.setItem("tyxnet_client_token",state.token);$("#password").value="";showDevices();await loadDevices()}catch(error){$("#login-error").textContent=error.message}});
$("#logout").addEventListener("click",async()=>{try{await request("/api/management/logout",{method:"POST"})}catch{}state.token="";sessionStorage.removeItem("tyxnet_client_token");showManagementLogin()});
$("#refresh-devices").addEventListener("click",()=>loadDevices().catch(error=>toast(error.message,true)));
$("#startup-enabled").addEventListener("change",async event=>{const enabled=event.target.checked;event.target.disabled=true;try{await request("/api/management/startup",{method:"PATCH",body:JSON.stringify({enabled})});toast(enabled?"Startup enabled.":"Startup disabled.")}catch(error){event.target.checked=!enabled;toast(error.message,true)}finally{event.target.disabled=false}});
$("#device-grid").addEventListener("click",async event=>{const button=event.target.closest("button[data-action]");if(!button)return;const action=button.dataset.action,id=button.closest("[data-device]").dataset.device;if((action==="restart"||action==="shutdown")&&!confirm(`Queue ${action} for this device?`))return;try{await request(`/api/management/devices/${encodeURIComponent(id)}/${action}`,{method:"POST"});toast(`${action} command queued.`)}catch(error){toast(error.message,true)}});
refreshLocal().then(()=>{if(state.configured)return bootManagement()});setInterval(refreshLocal,3000);setInterval(()=>{if(state.user)loadDevices().catch(()=>{})},10000);
